return {
	['clockConfigVersion'] = 2,
	['clockVisible'] = true,
	['clockAllowDrag'] = true,
	['clockPresetIndex'] = 1,
	['clockTimeFormatIndex'] = 1,
	['clockStyleIndex'] = 2,
	['clockTextSize'] = 0.6,
	['clockTextSizeIndex'] = 6,
	['clockTextColourIndex'] = 1,
	['clockTextColourRef'] = 'WHITE',
	['clockBackColourIndex'] = 19,
	['clockBackColourRef'] = 'DYN_UI.MAIN',
	['clockX'] = 0.80189,
	['clockY'] = -0.65535,
}
