[manifest]
version = '1.0.0'
dump_lua = true
priority = 1

[[patches]]
[patches.module]
source = 'moveablecontainer.lua'
before = 'main.lua'
name = 'systemclock.moveablecontainer'

[[patches]]
[patches.module]
source = 'utilities.lua'
before = 'main.lua'
name = 'systemclock.utilities'

[[patches]]
[patches.module]
source = 'config.lua'
before = 'main.lua'
name = 'systemclock.config'

[[patches]]
[patches.module]
source = 'config_ui.lua'
before = 'main.lua'
name = 'systemclock.config_ui'

[[patches]]
[patches.module]
source = 'clock_ui.lua'
before = 'main.lua'
name = 'systemclock.clock_ui'

[[patches]]
[patches.module]
source = 'core.lua'
before = 'main.lua'
name = 'systemclock.core'

[[patches]]
[patches.copy]
target = 'main.lua'
position = 'append'
sources = [
    'init.lua'
]